//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TkanEntities : DbContext
    {
        public TkanEntities()
            : base("name=TkanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryProduct> CategoryProduct { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<EdnIzmer> EdnIzmer { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<OrderBuy> OrderBuy { get; set; }
        public virtual DbSet<PointOfIssue> PointOfIssue { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sreet> Sreet { get; set; }
        public virtual DbSet<Statys> Statys { get; set; }
        public virtual DbSet<Suplier> Suplier { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
