//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderBuy = new HashSet<OrderBuy>();
        }
    
        public int ID { get; set; }
        public string VendorCode { get; set; }
        public string Title { get; set; }
        public Nullable<int> EdnIzmerID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> MaxDiscount { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> SuplierID { get; set; }
        public Nullable<int> CategoryProductID { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> CountCtock { get; set; }
        public string Information { get; set; }
        public byte[] ImageProduct { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
        public virtual EdnIzmer EdnIzmer { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBuy> OrderBuy { get; set; }
        public virtual Suplier Suplier { get; set; }
    }
}
