//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBuy
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CountProduct { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> PointOfIssueID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ReceiptCode { get; set; }
        public Nullable<int> StatysID { get; set; }
    
        public virtual PointOfIssue PointOfIssue { get; set; }
        public virtual Product Product { get; set; }
        public virtual Statys Statys { get; set; }
        public virtual User User { get; set; }
    }
}
